### PR TITLE
GitHub Actions for build check on linux

### LINKED ISSUE #5: Missing CI/CD
I suggest to create workflow for build check and testing :)

### PR DESCRIPTION
**Pull request by guerinoni**
This close #5.

Squash and merge.

### CODE REVIEW

**Comment by Foadsf** [comment]
@guerinoni I will look into this tonight. Are you on Discord too? 

https://discord.gg/nTRbdpY

**Comment by guerinoni** [comment]
@Foadsf 
After I will join... I wanna improve this repo :)

**Comment by Foadsf** [comment]
@guerinoni good job man.

**Review by pratikpc — APPROVED** [review]

**Comment by Mihaylov93** [comment]
Don´t forget to squash before merging.

**Comment by Foadsf** [comment]
@Mihaylov93 what do you mean by squash? 🤔

**Comment by Mihaylov93** [comment]
Its an option of git rebase, https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Currently the history is:

- improve .gitignore …
- Add build workflow …
- fixup! Add build workflow
- fixup! fixup! Add build workflow
- fixup! fixup! fixup! Add build workflow

with a git rebase could be squashed to be like 
- improve .gitignore …
- Add build workflow …

while maintaining the changes, to not pollute the branch

@guerinoni You could use git commit --amend, that rewrites your last commit. Its very useful when you just commited and forgot small changes.

**Pull request merged**
