### PR TITLE
Clean structure of project

### LINKED ISSUE #17: cleaning the build_XX folder
putting the `SimulIDE_Build.pro` file in the `build_XX` folder seems like a bad practice to me. we should

- move the `SimulIDE_Build.pro` to the root folder
- remove the `build_XX` and put it and the `build` directories in the `.gitignore` file 

Idelally we should have a compiling instructions of

   - `mkdir build`
   - `cd build`
   - `qmake ..`
   - `make`

and make sure the `build`  folders never end up in the git history.

### PR DESCRIPTION
**Pull request by guerinoni**
In thi way we don't have unused folder, buid dir is configurable
when you build project and I moved source in separe file then main
configurations.
This close #17 

Signed-off-by: Federico Guerinoni <guerinoni.federico@gmail.com>

### CODE REVIEW

**Comment by Mihaylov93** [comment]
Oh I just pushed this kind of clean on dev

**Comment by guerinoni** [comment]
@Mihaylov93 If this works we can merge it on master :)

**Comment by Mihaylov93** [comment]
Master is already behind dev https://github.com/SimulIDE/SimulIDE/tree/dev

**Comment by Mihaylov93** [comment]
I should revert and push it through my fork

**Comment by guerinoni** [comment]
Dev branch is useless IMHO

**Comment by Mihaylov93** [comment]
Done, https://github.com/SimulIDE/SimulIDE/pull/23

**Comment by guerinoni** [comment]
@Mihaylov93 Then I should remove this PR?

**Comment by Mihaylov93** [comment]
We basically did the same, at first I was thinking about $$PWD but then I wondered if expanding that variable on each line would add overhead, then I thought doing something like PRO_DIR = $$PWD and only expand it once, but in the end I realized that we can use . instead of .. (because before we had to go 1 level back)

**Comment by guerinoni** [comment]
We can merge this for refactoring and your for mingw handling :)

**Comment by Mihaylov93** [comment]
But before merging this to master, first align master with Dev

**Pull request merged**
